version: '3'
services:
  gethapier-api-server:
    build: .
    volumes:
      - ./:/code
      - /code/node_modules  # Excludes node_modules
      - ./.firebase/emulators/:/opt/workspace:cached
      - ./.firebase/bin/:/root/.cache:cached
      - ./.firebase/config/:/root/.config:cached
    ports:
      - "9229:9229"
      - "9800-9806:9800-9806" # expose for external/web consumption
    environment:
      # Credentials URL
      - GOOGLE_APPLICATION_CREDENTIALS=/code/service_account.json
      - GCLOUD_PROJECT=gethapier
    command: bash
    tty: true
